services:
  postgres:
    image: postgres:16
    container_name: loginSystem_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: login_system
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: